section_3
Mihai-Viorel/team-project-1 pull request #7
Opened 2024-08-27 21:30 UTC by RoxanaIliasi

2024-08-28 20:34 UTC, Mihai-Viorel submitted a review, later dismissed

2024-08-28 20:39 UTC, Mihai-Viorel requested changes
Tot codul pentru sectiunea 3 de css trebuie mutat in fisierul 5_section3.css 
(la fel cum ai procedat si cand ai facut html-ul)

Altfel, daca te uiti, conflictele apar in fisierul 3_section1.css deoarece el pe main vede schimbarile facute pt sectiunea 1 in fisierul 3_section1.css

2024-08-29 04:25 UTC, RoxanaIliasi commented
Scuze, chiar nu am observat ca am scris codul in fisierul css section_1.
Am mutat codul in fisierul corect, am dat chiar doua commi-uri (pt al doilea commit am scris un comentariu doar), dar nu imi mai apare pull request dupa ce dau commit.
Sper ca poti vedea modificarile

2024-08-29 16:30 UTC, Mihai-Viorel approved these changes

2024-08-29 16:31 UTC, merged